# Generated by Django 4.2.22 on 2026-02-03 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0067_issue_cached_display_title_es_and_more'),
        ('submission', '0082_article_abstract_es_article_title_es_section_name_es_and_more'),
        ('ezid', '0002_auto_20221013_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueDoiRefreshHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_refresh', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Success'), (4, 'Failure')], default=1)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.issue')),
            ],
            options={
                'ordering': ['-date_refresh'],
            },
        ),
        migrations.CreateModel(
            name='ArticleDoiRefreshHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_refresh', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Success'), (4, 'Failure')], default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('issue_pub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezid.issuedoirefreshhistory')),
            ],
            options={
                'ordering': ['-date_refresh'],
            },
        ),
    ]
