# Generated by Django 4.2.22 on 2026-02-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezid', '0003_issuedoirefreshhistory_articledoirefreshhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articledoirefreshhistory',
            old_name='issue_pub',
            new_name='issue_hist',
        ),
        migrations.AlterField(
            model_name='articledoirefreshhistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Success'), (4, 'Failure'), (5, 'Aborted')], default=1),
        ),
        migrations.AlterField(
            model_name='issuedoirefreshhistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Success'), (4, 'Failure'), (5, 'Aborted')], default=1),
        ),
    ]
